const UPDATE_USER_STATE = {
    type: 'UPDATE_USER_STATE',
    action: {
      UPDATE_LOGIN: 'UPDATE_LOGIN',
      UPDATE_LOGOUT: 'UPDATE_LOGOUT',
      UPDATE_SIGNUP: 'UPDATE_SIGNUP',
      UPDATE_COUNTRY:"UPDATE_COUNTRY",
      BASIC_AUTO_POPULATE_INFO : "BASIC_AUTO_POPULATE_INFO",
    }
}

export default UPDATE_USER_STATE;
